# Generated by Django 4.2.16 on 2024-12-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_thread_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
